# Generated by Django 3.2.6 on 2022-02-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_product_add_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='add_by',
            field=models.CharField(max_length=500),
        ),
    ]
